id: PADDC1AC4
initial_creation_type: input
source_metadata:
  title: Vimalamitra
  language: en
  description: 'Texts by and about the eighth-century paṇḍita and Dzogchen master
    Vimalamitra (dri med bshes gnyen), who is said to have attained the rainbow body:'
  volume:
    487b4d78fa7946bfa7107079d4ede790:
      title: Prayer to the Great Paṇḍita Vimalamitra
      parent: Prayers
created_at: '2022-03-01T02:27:05.808591'
last_modified_at: '2022-03-01T02:27:05.808597'
